### ISSUE TITLE
Build multiple sass files from one rule

### ISSUE THREAD

**Issue by stoltene2** [bazelbuild/rules_sass#22]
I encountered a need to compile multiple sass files in a large angular application. It would be a great feature to support globs of sass files.

I created a new rule `multi_sass_binary` which accomplishes this task.

**Comment by perezd** [comment]
I understand what this does functionally, but I'm but clear on how it would
be used practically. Generally, Bazel rules should generate a static number
of outputs per target, from the docs:

"...
If an action generates an unknown number of outputs and you want to keep
them all, you must group them in a single file (e.g., a zip, tar, or other
archive format). This way, you will be able to deterministically declare
your outputs."

Citation: https://docs.bazel.build/versions/master/skylark/rules.html

I'm on my phone and haven't checked, is this generating a zip or something?
Otherwise if it's a dynamic output set, I'd prefer to not endorse this
officially. Thoughts?

Thanks for reaching out and taking the time to discuss!
