### ISSUE TITLE
Setup guide names 1.14.3 in example, but does not work for that release

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/rules_sass#56]
It looks like in 8b61ad6953fde55031658e1731c335220f881369 setup for rules_sass was overhauled quite a bit. The setup guide was also updated in that commit, and says that setup should work for 1.14.3

However, the referenced bzls, for example, `//:defs.bzl`, are not in that release. (In fact, they were created as part of 8b61ad6953fde55031658e1731c335220f881369

**Comment by DevVersion** [comment]
Yeah, it's a bit odd since `v1.14.3` technically doesn't include Sass `1.14.3` due to some issues with the `sassbot` not updating the version, but just cutting a release.

We could either just wait for the next update of Sass, or just update the docs in the meanwhile. I think the latter definitely makes more sense.
